// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4Exponential_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Gamma_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4GenF_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4GenGamma_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Gompertz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4PolyWeibull_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RP_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4WeibullAF_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4WeibullPH_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4logLogistic_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4logNormal_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4Exponential_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Exponential_mod, 0},
    {"_rcpp_module_boot_stan_fit4Gamma_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Gamma_mod, 0},
    {"_rcpp_module_boot_stan_fit4GenF_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4GenF_mod, 0},
    {"_rcpp_module_boot_stan_fit4GenGamma_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4GenGamma_mod, 0},
    {"_rcpp_module_boot_stan_fit4Gompertz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Gompertz_mod, 0},
    {"_rcpp_module_boot_stan_fit4PolyWeibull_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4PolyWeibull_mod, 0},
    {"_rcpp_module_boot_stan_fit4RP_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RP_mod, 0},
    {"_rcpp_module_boot_stan_fit4WeibullAF_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4WeibullAF_mod, 0},
    {"_rcpp_module_boot_stan_fit4WeibullPH_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4WeibullPH_mod, 0},
    {"_rcpp_module_boot_stan_fit4logLogistic_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4logLogistic_mod, 0},
    {"_rcpp_module_boot_stan_fit4logNormal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4logNormal_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_survHE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
