#' Plot survival curves for the models fitted using \code{fit.models}
#' 
#' Plots the results of model fit.
#' 
#' 
#' @param x Either a single object generated by the call to \code{fit.models}
#' or a list of such objects. 
#' @param exArgs list of extra options passed to \code{plot.survHE}. These 
#' include whether the KM curve should be added \code{add.km} and whether
#' the user specifies a profile of covariates (in the list \code{newdata}).
#' Other possibilities are additional (mainly graphical) options. 
#' These are: \code{xlab} = a string with the label for the
#' x-axis (default = "time") \code{ylab} = a string with the label for the
#' y-axis (default = "Survival") \code{lab.trt} = a (vector of) string(s)
#' indicating the labels associated with the strata defining the different
#' survival curves to plot. Default to the value used by the Kaplan Meier
#' estimate given in \code{fit.models} \code{cex.trt} = factor by which the
#' size of the font used to write the strata is resized (default = 0.8)
#' \code{n.risk} = logical. If TRUE (defaults) writes the number at risk at
#' different time points (as determined by the Kaplan Meier estimate)
#' \code{newdata} = a list (of lists) providing the values for the relevant
#' covariates If NULL, then will use the mean values for the covariates if at
#' least one is a continuous variable, or the combination of the categorical
#' covariates. \code{xlim} = a vector determining the limits for the x-axis
#' \code{colors} = a vector of characters defining the colours in which to plot
#' the different survival curves \code{labs} = a vector of characters defining
#' the names of the models fitted \code{add.km} = TRUE (whether to also add the
#' Kaplan Meier estimates of the data) \code{legend} = TRUE (whether to also 
#' add the legend to the graph)
#' @note Something will go here
#' @author Gianluca Baio
#' @seealso Something will go here
#' @references Something will go here
#' @keywords Parametric survival models
#' @examples
#' 
#' data(bc)
#' 
#' mle = fit.models(formula=Surv(recyrs,censrec)~group,data=bc,
#'     distr="exp",method="mle")
#' plot(mle)
#' 
plot_ggplot_survHE <- function(x,exArgs) {
  
  # Check some basic inputs - if not specified by the user (and stored in 'exArgs', then
  # sets up defaults to be used in the other functions)
  # t = time to plot on the x-axis (default = the times in the original data/survHE object)
  if (!exists("t",exArgs)) {t <- sort(unique(x$misc$km$time))} else {t <- exArgs$t}
  # newdata = possible list with a profile of covariates (default = NULL)
  if (!exists("newdata",exArgs)) {newdata <- NULL} else {newdata <- exArgs$newdata}
  # Should a KM curve be added to the plot (default = F)
  if (!exists("add.km",exArgs)) {add.km <- FALSE} else {add.km <- exArgs$add.km}
  # What model should be used from the object 'x'?
  if (!exists("mods",exArgs)) {mods=1} else {mods=exArgs$mods}
  
  ### These can also be specified (but the functions below need to be modified to account for these new options)
  ###
  # if (is.null(exArgs$xlab)) {xl <- "time"} else {xl <- exArgs$xlab}
  # if (is.null(exArgs$ylab)) {yl <- "Survival"} else {yl <- exArgs$ylab}
  # if (is.null(exArgs$lab.trt)) {lab.trt <- names(x$misc$km$strata)} else {lab.trt<-exArgs$lab.trt}
  # if (is.null(exArgs$cex.trt)) {cex.trt <- 0.8} else {cex.trt <- exArgs$cex.trt}
  # if (is.null(exArgs$n.risk)) {nrisk <- FALSE} else {nrisk <- exArgs$n.risk}
  # if (is.null(exArgs$main)) {main <- ""} else {main <- exArgs$main}
  # if (is.null(exArgs$cex.lab)) {cex.lab <- 0.8} else {cex.lab <- exArgs$cex.lab}
  # if (is.null(exArgs$legend)) {legend=TRUE} else (legend=FALSE)
  # if (exists("colour",exArgs)) {colour=exArgs$colour} else (colour="blue")
  
  # First checks the class of the input
  if(class(x)=="survHE") {
    # If x is a 'survHE' object, then there's only one object to deal with
    surv.curv=make_surv_curve_plot(x,mods,nsim=1,t,newdata,add.km)
  }
  # If it's a list made by 'survHE' objects then do something more complex
  if(class(x)=="list") {
    
  }
  # Now prints the plot
  surv.curv
}


### Do I need a specialised helper function here? Can this be embedded in 'plot_ggplot_survHE'? 
### NB: this may be helpful to have as a separate function to fun PSA plots...
make_surv_curve_plot <- function(x,mods=1:length(x$models),nsim=1,t=NULL,newdata=NULL,add.km=FALSE) {
  # Defines the times to allow for extrapolation
  if(is.null(t)) {
    t <- sort(unique(x$misc$km$time))
  }
  
  s=lapply(1:length(x$models),function(i) {
    make.surv(x,mod=i,t=t,nsim=nsim,newdata=newdata)
  })
  strata=lapply(1:length(s),function(i) {
    lapply(1:nrow(s[[i]]$des.mat),function(x){
      s[[i]]$des.mat %>% as_tibble() %>% select(-matches("(Intercept)",everything())) %>% slice(x) %>% 
        round(digits=2) %>% mutate(strata=paste0(names(.),"=",.,collapse=","))
    }) %>% bind_rows(.) %>% select(strata)
  })
  toplot=lapply(1:length(mods),function(i) {
    lapply(1:length(s[[mods[i]]]$S),function(j) {
      s[[mods[i]]]$S[[j]] %>% bind_cols(strata=as.factor(strata[[mods[i]]][j,]),model_name=as.factor(names(x$models)[mods[i]]))
    })
  }) %>% bind_rows(.)
  
  surv.curv=ggplot() +
    geom_line(data=toplot,aes(x=t,y=S,group=model_name:strata,col=model_name,linetype=strata),size=.9) +
    theme_bw() + 
    theme(axis.text.x = element_text(color="black",size=12,angle=0,hjust=.5,vjust=.5),
          axis.text.y = element_text(color="black",size=12,angle=0,hjust=.5,vjust=.5),
          axis.title.x = element_text(color="black",size=14,angle=0,hjust=.5,vjust=.5),
          axis.title.y = element_text(color="black",size=14,angle=90,hjust=.5,vjust=.5)) +
    theme(axis.line = element_line(colour = "black"),
          #panel.grid.major = element_blank(),
          #panel.grid.minor = element_blank(),
          #panel.border = element_blank(),
          panel.background = element_blank(),
          panel.border = element_blank(),
          plot.title = element_text(size=10, face="bold")) +
    theme(legend.position=c(.75,.9),
          legend.title=element_text(size=15,face="bold"),
          #legend.title = element_blank(),
          legend.text = element_text(colour="black", size=14, face="plain"),
          legend.background=element_blank()) +
    labs(y="Survival",x="Time",title=NULL,
         color=ifelse(length(mods)==1,"Model","Models"),
         linetype="Profile") + 
    # This ensures that the model legend is always before the profile legend
    guides(color=guide_legend(order=1),
           linetype=guide_legend(order=2))
  # If uses morethan 1 simulation from distribution of survival curves, then add ribbon
  if(nsim>1) {
    surv.curv=surv.curv+geom_ribbon(data=toplot,aes(x=t,y=S,ymin=low,ymax=upp,group=model_name:strata),alpha=.2)
  }
  
  # Add KM plot? 
  if(add.km==TRUE) {
    # If the number of strata in the KM computed in 'fit.models' is not the same as the 
    # number of rows in the design matrix from 'make.surv', then re-do a KM with no covariates
    if(length(x$misc$km$strata)!=nrow(s[[1]]$des.mat)){
      x$misc$km=rms::npsurv(update(x$misc$formula,~1),data=x$misc$data)
      x$misc$km$call$formula=as.formula(deparse(update(x$misc$formula,~1)))
    }
    # Now uses info in the KM table in the survHE object to create a dataset to plot
    datakm=bind_cols(t=x$misc$km$time,n.risk=x$misc$km$n.risk,n.event=x$misc$km$n.event,
                  n.censor=x$misc$km$n.censor,S=x$misc$km$surv,lower=x$misc$km$lower,
                  upper=x$misc$km$upper) %>% mutate(model_name="Kaplan Meier")
    # If 'strata' is not in the KM object (will happen if there's only 1)
    if(is.null(x$misc$km$strata)) {
      datakm$strata=as.factor("all")
    } else {
      datakm$strata=as.factor(rep(1:length(x$misc$km$strata),x$misc$km$strata))
    }
    surv.curv=surv.curv+geom_line(data=datakm,aes(t,S,group=as.factor(strata)),color="darkgrey") + 
      geom_ribbon(data=datakm,aes(x=t,y=S,ymin=lower,ymax=upper,group=as.factor(strata)),alpha=.2) 
  }
  ## If I want to change the appearance of the elements I may need to do something like
  # +scale_linetype_manual(labels=c("Control","Treated"),values=c("dotdash","solid"))
  # +scale_color_manual(values=cols) (if cols is specified by the user and is a vector of colours - one per model)
  #...
  surv.curv
}


make_KM_plot <- function(x,conf.int=TRUE,risk.table=TRUE,risk.table.col="strata",
                         palette=NULL,legend.labs=NULL) {
  # Helper function to plot the KM curve 
  if(is.null(palette)) {
    if (length(x$misc$km$strata)>0) {
      greyscale=colorRampPalette(c("grey20","grey80"))
      palette=greyscale(length(x$misc$km$strata))
    } else {
      palette="black"
    }
  }
  kmplot <- survminer::ggsurvplot(fit=x$misc$km,data=x$misc$data,
                                  conf.int=TRUE,
                                  risk.table = risk.table,        
                                  ##risk.table.col = "strata",
                                  palette = palette,
                                  legend.labs = legend.labs,
                                  risk.table.height = 0.25, # Useful to change when you have multiple groups
                                  ggtheme = ggplot2::theme_bw()
  )
  kmplot
}
